// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteSecret(arg1) {
  return window['go']['main']['App']['DeleteSecret'](arg1);
}

export function GetSecretsList() {
  return window['go']['main']['App']['GetSecretsList']();
}

export function InsertSecret(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['InsertSecret'](arg1, arg2, arg3, arg4);
}

export function RecognizeQRCode(arg1) {
  return window['go']['main']['App']['RecognizeQRCode'](arg1);
}

export function UpdateSecret(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateSecret'](arg1, arg2, arg3, arg4);
}
