// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function GetSecretsList():Promise<Array<model.Secret>>;

export function InsertSecret(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;
