name: Build and Release

on:
  push:
    tags:
      - 'v*'

# 显式声明权限
permissions:
  contents: write  # 这是创建发布和上传文件所需的权限

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    needs: build-and-release
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'
          check-latest: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Create .env file
        run: |
          echo "MASTER_PASSWORD=${{ secrets.MASTER_PASSWORD }}" > .env
        shell: powershell

      - name: Build for Windows
        run: |
          ./build.ps1
        shell: powershell
        env:
          MASTER_PASSWORD: ${{ secrets.MASTER_PASSWORD }}

      - name: Package Windows build
        run: |
          # 创建打包目录
          mkdir -p release
          # 复制生成的可执行文件和资源
          cp -r build/bin/* release/
          # 创建 ZIP 文件
          Compress-Archive -Path release/* -DestinationPath Euthenticator-windows-${{ github.ref_name }}.zip
        shell: powershell

      - name: Upload Windows build
        uses: softprops/action-gh-release@v1
        with:
          files: Euthenticator-windows-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-linux:
    needs: build-and-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'
          check-latest: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          # 安装 WebKit2GTK 依赖和其他构建必需的包
          sudo apt-get install -y build-essential libgtk-3-dev libglib2.0-dev
          # 尝试安装 WebKit2GTK 4.1 (较新的 Ubuntu 版本)
          sudo apt-get install -y libwebkit2gtk-4.1-dev
          # 创建 webkit2gtk-4.0.pc 的符号链接指向 webkit2gtk-4.1.pc
          # 这解决了 Wails 寻找 webkit2gtk-4.0 但系统只有 webkit2gtk-4.1 的问题
          sudo ln -sf /usr/lib/x86_64-linux-gnu/pkgconfig/webkit2gtk-4.1.pc /usr/lib/x86_64-linux-gnu/pkgconfig/webkit2gtk-4.0.pc
          # 安装其他可能需要的依赖
          sudo apt-get install -y pkg-config

      - name: Create .env file
        run: |
          echo "MASTER_PASSWORD=${{ secrets.MASTER_PASSWORD }}" > .env
        shell: bash

      - name: Build for Linux
        run: |
          chmod +x ./build.sh
          ./build.sh
        shell: bash
        env:
          MASTER_PASSWORD: ${{ secrets.MASTER_PASSWORD }}

      - name: Package Linux build
        run: |
          # 创建打包目录
          mkdir -p release
          # 复制生成的可执行文件和资源
          cp -r build/bin/* release/
          # 创建压缩文件
          tar -czvf Euthenticator-linux-${{ github.ref_name }}.tar.gz -C release .

      - name: Upload Linux build
        uses: softprops/action-gh-release@v1
        with:
          files: Euthenticator-linux-${{ github.ref_name }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}